//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_okul2_veritabani_projesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Notlar
    {
        public long kayit_no { get; set; }
        [Required(ErrorMessage ="Öðrenci Seçilmeli")]
        public int og_no { get; set; }
        [Required(ErrorMessage = "DErs Seçilmeli")]
        public byte ders_no { get; set; }
        [Range(0,100,ErrorMessage ="Not Deðeri 0 ile 100 arasýnda olmalý" )]
        public Nullable<byte> yaz1 { get; set; }
        public Nullable<byte> yaz2 { get; set; }
        public Nullable<byte> soz { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
