//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_okul2_veritabani_projesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Notlar = new HashSet<Notlar>();
        }
        [Required(ErrorMessage ="Öðrenci No Gerekli")]
        public int og_no { get; set; }
        [Required(ErrorMessage = "Ad soyad Girilmesi Zorunlu")]
        [StringLength(30,ErrorMessage ="Ad soyad En Fazla 30 Karakter olmalý")]
        public string og_ad_soyad { get; set; }
        [Required(ErrorMessage = "Doðum Tarihi Gerekli")]
        public System.DateTime dog_tar { get; set; }
        [Required(ErrorMessage = "Tc Kimlik Gerekli")]
        public long tc_kimlik { get; set; }
      
        public string adres { get; set; }
        [Required(ErrorMessage = "Email Gerekli"),EmailAddress(ErrorMessage ="Doðru Email giriniz")]

        public string email { get; set; }
        [Required(ErrorMessage = "Sýnýf Seçmek Gerekli")]
        public string sinif_adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notlar> Notlar { get; set; }
        public virtual siniflar siniflar { get; set; }
    }
}
