//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_projesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class hastalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hastalar()
        {
            this.Yatislar = new HashSet<Yatislar>();
        }
    
        public int hasta_no { get; set; }
        [Required(ErrorMessage = "Tc Girmek zorunlu")]
        public long hasta_tc { get; set; }
        [Required(ErrorMessage = "hasta adý zorunlu")]
        public string hasta_adi { get; set; }
        public string hasta_adres { get; set; }
        
        [Required(ErrorMessage ="Cinsiyet Seçmek zorunlu")]
        public bool? hasta_cinsiyet { get; set; }//hiçbir alan seçilmesse boþ gelir default false olur o yüzden ? ile boþ olabilir olarak belirtiyoruz
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yatislar> Yatislar { get; set; }
    }
}
